mobile_manipulator_controller:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers --------------------------------------
  motor_fl_position_controller:
    type: effort_controllers/JointPositionController
    joint: motor_fl
    pid: {p: 100.0, i: 0.01, d: 10.0}
  motor_fr_position_controller:
    type: effort_controllers/JointPositionController
    joint: motor_fr
    pid: {p: 100.0, i: 0.01, d: 10.0}
  motor_br_position_controller:
    type: effort_controllers/JointPositionController
    joint: motor_br
    pid: {p: 100.0, i: 0.01, d: 10.0}
  shoulder_right_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_right_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  shoulder_left_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_left_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  motor_bl_position_controller:
    type: effort_controllers/JointPositionController
    joint: motor_bl
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arm_right_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_right_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  arm_left_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: arm_left_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  forearm_right_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: forearm_right_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  forearm_left_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: forearm_left_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wrist_right_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_right_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wrist_left_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_left_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  palm_right_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: palm_right_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  palm_left_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: palm_left_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  knuckle_right_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: knuckle_right_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  knuckle_left_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: knuckle_left_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  finger_right_1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: finger_right_1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  finger_right_2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: finger_right_2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  finger_left_1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: finger_left_1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  finger_left_2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: finger_left_2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
