manipulator_controller:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers --------------------------------------
  base_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  shoulder_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  elbow_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: elbow_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  wrist_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  hand_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: hand_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  palm_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: palm_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  finger_1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: finger_1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  finger_2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: finger_2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
