manipulator_controller:
  # Publish all joint states -----------------------------------
  /manipulator/joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers --------------------------------------
  /manipulator/base_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  /manipulator/shoulder_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  /manipulator/elbow_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: elbow_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  /manipulator/wrist_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  /manipulator/hand_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: hand_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  /manipulator/palm_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: palm_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  /manipulator/finger_1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: finger_1_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  /manipulator/finger_2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: finger_2_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
