# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm_right
  joint_model_group_pose: default_arm_right
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - shoulder_left_joint
    - arm_left_joint
    - forearm_left_joint
    - wrist_left_joint
    - palm_left_joint
    - knuckle_left_joint
    - finger_left_1_joint
    - finger_left_2_joint
    - shoulder_right_joint
    - arm_right_joint
    - forearm_right_joint
    - wrist_right_joint
    - palm_right_joint
    - knuckle_right_joint
    - finger_right_1_joint
    - finger_right_2_joint
    - motor_bl
    - motor_br
    - motor_fl
    - motor_fr
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
arm_left_controller:
  type: position_controllers/JointPositionController
  joints:
    - shoulder_left_joint
    - arm_left_joint
    - forearm_left_joint
    - wrist_left_joint
    - palm_left_joint
  gains:
    shoulder_left_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_left_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    forearm_left_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_left_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    palm_left_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
arm_right_controller:
  type: position_controllers/JointPositionController
  joints:
    - shoulder_right_joint
    - arm_right_joint
    - forearm_right_joint
    - wrist_right_joint
    - palm_right_joint
  gains:
    shoulder_right_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    arm_right_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    forearm_right_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    wrist_right_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    palm_right_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1